# Вариант №3
from tkinter import *
from tkinter.ttk import Combobox
from tkinter.ttk import Checkbutton
from tkinter import scrolledtext
window = Tk()
window.title('Анкета')
window.geometry('732x567')
Label(text='Анкета Web-разработчика', font='arial 19').place(x=0, y=5)
Label(text='Регистрационное имя', font='arial 13').place(x=0, y=70)
Entry(width=21, font='arial 13').place(x=200, y=72)
Label(text='Пароль', font='arial 13').place(x=0, y=110)
Entry(width=21, font='arial 13').place(x=200, y=112)
Entry(width=21, font='arial 13').place(x=200, y=142)
Label(text='Ваша специализация', font='arial 13').place(x=0, y=180)
combo = Combobox(window, width=21, values=['Web-мастер'])
combo.current(0)
combo.place(x=200, y=182)
Label(text='Пол', font='arial 13').place(x=0, y=220)
selected = IntVar()
Radiobutton(window, text='М', value=0, variable=selected).place(x=200, y=222)
Radiobutton(window, text='Ж', value=1, variable=selected).place(x=240, y=222)
Label(text='Ваши навыки', font='arial 13').place(x=0, y=260)
chk = BooleanVar()
chk.set(True)
Checkbutton(window, text='знание HTML и CSS', variable=chk).place(x=200, y=262)
chk1 = BooleanVar()
chk1.set(False)
Checkbutton(window, text='знание Perl', variable=chk1).place(x=200, y=282)
chk2 = BooleanVar()
chk2.set(False)
Checkbutton(window, text='знание ASP', variable=chk2).place(x=200, y=302)
chk3 = BooleanVar()
chk3.set(False)
Checkbutton(window, text='знание Adobe Photoshop', variable=chk3).place(x=200, y=322)
chk4 = BooleanVar()
chk4.set(False)
Checkbutton(window, text='знание JAVA', variable=chk4).place(x=200, y=342)
chk5 = BooleanVar()
chk5.set(False)
Checkbutton(window, text='знание JavaScript', variable=chk5).place(x=200, y=362)
chk6 = BooleanVar()
chk6.set(False)
Checkbutton(window, text='знание Flash', variable=chk6).place(x=200, y=382)
Label(text='Дополнительные сведения', font='arial 12').place(x=0, y=410)
scrolledtext.ScrolledText(window, width=40, height=4).place(x=200, y=412)
Button(text="зарегистрировать", width=25).place(x=0, y=520)
Button(text="очистить форму", width=25).place(x=190, y=520)
window.mainloop()
